language: php

php:
    - 7.2
    - 7.3
    - 7.4

matrix:
    include:
        - php: 7.3
          env: SYMFONY_VERSION=4.4.*
        - php: 7.4
          env: SYMFONY_VERSION=5.1.*

env:
    - SYMFONY_VERSION=3.4.*

before_script:
    - composer self-update
    - composer require symfony/config:${SYMFONY_VERSION} --no-update
    - composer require symfony/dependency-injection:${SYMFONY_VERSION} --no-update
    - composer require symfony/http-kernel:${SYMFONY_VERSION} --no-update
    - composer require symfony/framework-bundle:${SYMFONY_VERSION} --no-update
    - composer require symfony/phpunit-bridge:${SYMFONY_VERSION} --no-update
    - composer require symfony/twig-bundle:${SYMFONY_VERSION} --no-update
    - composer update --prefer-source
    - vendor/bin/simple-phpunit install

script: vendor/bin/simple-phpunit

notifications:
    email: laupi.frpar@gmail.com
