language: php

php:
    - 7.1
    - 7.2
    - 7.3
    - hhvm

matrix:
    allow_failures:
        - php: hhvm
        - php: 7.1
          env: SYMFONY_VERSION=4.3.*
        - php: 7.2
          env: SYMFONY_VERSION=4.3.*
        - php: 7.3
          env: SYMFONY_VERSION=4.3.*
    include:
        - php: 7.1
          env: SYMFONY_VERSION=3.4.*
        - php: 7.1
          env: SYMFONY_VERSION=4.2.*
        - php: 7.2
          env: SYMFONY_VERSION=3.4.*
        - php: 7.2
          env: SYMFONY_VERSION=4.2.*
        - php: 7.3
          env: SYMFONY_VERSION=3.4.*
        - php: 7.3
          env: SYMFONY_VERSION=4.2.*


env:
    - SYMFONY_VERSION=3.4.*

before_script:
    - composer self-update
    - composer require symfony/config:${SYMFONY_VERSION} --no-update
    - composer require symfony/dependency-injection:${SYMFONY_VERSION} --no-update
    - composer require symfony/http-kernel:${SYMFONY_VERSION} --no-update
    - composer update --prefer-source

script: phpunit

notifications:
    email: laupi.frpar@gmail.com
